services:
  php-fpm:
    image: php:8.1-fpm
    container_name: symfonyProject-php-fpm
    depends_on:
      - mysql

  php-cli:
    build:
      context: .
      dockerfile: docker/Dockerfile.php-cli
    volumes:
      - ./:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t ./public
    container_name: symfonyProject-php-cli
    ports:
      - "8080:8000"
 
  composer:
    image: composer:2
    container_name: symfonyProject-composer
    command: [require, twig, --ignore-platform-reqs]

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    container_name: symfonyProject-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"

volumes:
  mysql:
