services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: symfonyProject-nginx
    ports:
      - "8000:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: symfonyProject-php-fpm
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    container_name: symfonyProject-php-cli


 
  composer:
    build:
      context: .
      dockerfile: docker/composer/Dockerfile
    container_name: symfonyProject-composer
    command: [require, twig, --ignore-platform-reqs]

  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    container_name: symfonyProject-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"

volumes:
  mysql:
