controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# test redis delete after
redis_test:
    path: /redis/test
    controller: App\Controller\RedisTestController::test
